# Place this file in `/etc/keyd/default.conf`
# Run `sudo keyd reload` to reload configuration

[ids]
*

#
# Swedish    US
# p          p
# å          leftbrace
# l          l
# '          \
#
[altgr]

# AltGr+8 = [ on Swedish layout
p = G-8

# AltGr+9 = ] on Swedish layout
leftbrace = G-9

# AltGr+7 = { on Swedish layout
l = G-7

# AltGr+0 = } on Swedish layout
\ = G-0
